# Generated by Django 5.0.4 on 2024-04-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_author_description_author_bookcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authormap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookId', models.IntegerField()),
                ('authorId', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Authormap',
                'verbose_name_plural': 'Authormaps',
            },
        ),
    ]
